# Generated by Django 6.0.2 on 2026-04-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geopram_app', '0002_userprofile_points_userprofile_referral_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home_hero', 'Home - Hero Section'), ('home_services', 'Home - Services Section'), ('home_stats', 'Home - Stats Section'), ('home_software', 'Home - Software Section'), ('home_testimonials', 'Home - Testimonials Section'), ('home_cta', 'Home - CTA Section'), ('footer', 'Footer')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('page',)},
            },
        ),
    ]
